# Generated by Django 5.0.6 on 2025-02-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('segment', models.CharField(max_length=100)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('leader_name', models.CharField(blank=True, max_length=100, null=True)),
                ('leader_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('leader_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('team_size', models.IntegerField(default=1)),
                ('transaction_id', models.CharField(max_length=100)),
                ('members', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
