# Generated by Django 5.0.6 on 2025-02-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='leader_email',
            new_name='team_leader_email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='leader_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='leader_phone',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='members',
        ),
        migrations.AddField(
            model_name='registration',
            name='team_leader_name',
            field=models.CharField(default='rakesh', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='team_leader_phone',
            field=models.CharField(default='83949', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='team_members',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='team_size',
            field=models.IntegerField(),
        ),
    ]
